In [28]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [29]:
#load data
df = pd.read_csv('D:\PowerBI\Superstore\Superstore.csv', encoding='latin-1')

<>:2: SyntaxWarning: invalid escape sequence '\P'
<>:2: SyntaxWarning: invalid escape sequence '\P'
C:\Users\rahul\AppData\Local\Temp\ipykernel_10112\3091690338.py:2: SyntaxWarning: invalid escape sequence '\P'
  df = pd.read_csv('D:\PowerBI\Superstore\Superstore.csv', encoding='latin-1')

In [30]:
df.sample(5)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
8616,8617,CA-2016-165918,9/10/2016,9/14/2016,Standard Class,BD-11770,Bryan Davis,Consumer,United States,Edmonds,...,98026,West,OFF-PA-10000100,Office Supplies,Paper,Xerox 1945,81.980,2,0.0,40.1702
2428,2429,CA-2016-169922,6/11/2016,6/17/2016,Standard Class,MZ-17515,Mary Zewe,Corporate,United States,Arlington,...,76017,Central,OFF-BI-10001617,Office Supplies,Binders,GBC Wire Binding Combs,8.272,4,0.8,-13.6488
7211,7212,US-2016-119046,6/2/2016,6/6/2016,Standard Class,EH-13765,Edward Hooks,Corporate,United States,Seattle,...,98115,West,OFF-BI-10001078,Office Supplies,Binders,"Acco PRESSTEX Data Binder with Storage Hooks, ...",51.648,12,0.2,18.7224
4086,4087,CA-2016-111913,8/4/2016,8/6/2016,Second Class,LC-16930,Linda Cazamias,Corporate,United States,Sacramento,...,95823,West,OFF-BI-10003291,Office Supplies,Binders,Wilson Jones Leather-Like Binders with DublLoc...,20.952,3,0.2,7.0713
7945,7946,CA-2017-134194,12/25/2017,1/1/2018,Standard Class,GA-14725,Guy Armstrong,Consumer,United States,Dallas,...,75081,Central,OFF-BI-10001597,Office Supplies,Binders,"Wilson Jones Ledger-Size, Piano-Hinge Binder, ...",40.980,5,0.8,-65.5680

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

In [32]:
# Convert date columns to datetime format
df['Order Date'] = pd.to_datetime(df['Order Date'], format='%m/%d/%Y')
df['Ship Date'] = pd.to_datetime(df['Ship Date'], format='%m/%d/%Y')

In [33]:
#Looking for missing values
df.isnull().sum()
#looking for duplicates
df.duplicated().sum()

np.int64(0)

In [34]:
#Looking for statistics of numerical columns
df.describe()

,Row ID,Order Date,Ship Date,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9994,9994,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,2016-04-30 00:07:12.259355648,2016-05-03 23:06:58.571142912,55190.379428,229.858001,3.789574,0.156203,28.656896
min,1.000000,2014-01-03 00:00:00,2014-01-07 00:00:00,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,2015-05-23 00:00:00,2015-05-27 00:00:00,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,2016-06-26 00:00:00,2016-06-29 00:00:00,56430.500000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,2017-05-14 00:00:00,2017-05-18 00:00:00,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,2017-12-30 00:00:00,2018-01-05 00:00:00,99301.000000,22638.480000,14.000000,0.800000,8399.976000
std,2885.163629,NaN,NaN,32063.693350,623.245101,2.225110,0.206452,234.260108

In [ ]:
#adding some new columns for analysis
df['Profit Margin'] = (df['Profit'] / df['Sales'])
df["Order Year"] = df["Order Date"].dt.year
df["Order Month"] = df["Order Date"].dt.month
df["Shipping Days"] = (df["Ship Date"] - df["Order Date"]).dt.days

In [36]:
df = df.drop(columns=[
    "Row ID",
    "Postal Code",
    "Product ID",
    "Customer ID"
])

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       9994 non-null   object
 1   Order Date     9994 non-null   datetime64[ns]
 2   Ship Date      9994 non-null   datetime64[ns]
 3   Ship Mode      9994 non-null   object
 4   Customer Name  9994 non-null   object
 5   Segment        9994 non-null   object
 6   Country        9994 non-null   object
 7   City           9994 non-null   object
 8   State          9994 non-null   object
 9   Region         9994 non-null   object
 10  Category       9994 non-null   object
 11  Sub-Category   9994 non-null   object
 12  Product Name   9994 non-null   object
 13  Sales          9994 non-null   float64
 14  Quantity       9994 non-null   int64
 15  Discount       9994 non-null   float64
 16  Profit         9994 non-null   float64
 17  Profit Margin  9994 non-null   float64
 18  Order Year     9994 non-null   int32
 19  Order Month    9994 non-null   int32
 20  Shipping Days  9994 non-null   int64
dtypes: datetime64[ns](2), float64(4), int32(2), int64(2), object(11)
memory usage: 1.5+ MB

In [38]:
df.to_csv("clean_superstore_data.csv", index=False)